version: "3.9"
services:
  chanchito:
    build: .
    ports:
      - "3000:3000"
    links:
      - monguito
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      # Ruta del contenedor donde estan los datos
      - mongo-data:/data/db
#       # mysql -> /var/lib/mysql
#       # postgres -> /var/lib/postgresql/data
# Este volumes es para poder persistir los datos de mi contenedor de mongo
volumes:
  mongo-data:
